server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_project
    username: checker
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true

